//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 帮扶系统类图设计
//  @ File Name : User_view.java
//  @ Date : 2020/6/29
//  @ Author : 
//
//




public class User_view {
	public void displayUser() {
	
	}
	
	public void UpdateData() {
	
	}
}
