//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Control1.java
//  @ Date : 2020/6/27
//  @ Author : 
//
//




public class Control1 {
	public void request_login() {
	
	}
	
	public void request_taskcode() {
	
	}
	
	public void request_selectTask() {
	
	}
}
