//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 帮扶系统类图设计
//  @ File Name : Task.java
//  @ Date : 2020/6/29
//  @ Author : 
//
//




public class Task {
	private String Task_name;
	private String Task_Text;
	public void setTask() {
	
	}
	
	public String getTask() {
	
	}
}
