//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 帮扶系统类图设计
//  @ File Name : User.java
//  @ Date : 2020/6/29
//  @ Author : 
//
//




public class User {
	private String name;
	private String password;
	private String Email;
	public int Level;
	public void setName(String name) {
	
	}
	
	public void setPassword(String password) {
	
	}
	
	public void setEmail(String Email) {
	
	}
	
	public String getName() {
	
	}
	
	public String getPassword() {
	
	}
	
	public String getEmail() {
	
	}
}
